<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
	xmlns:tns="http://sample.org/bpel/echo/echo.bpelArtifacts"
	xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" 
	xmlns:wsdl="http://sample.org/wsdl/echo/echo.wsdl"
	xmlns:wsdl1="http://sample.org/wsdl/echo_service/echo_service.wsdl"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="echoArtifacts"
	targetNamespace="http://sample.org/bpel/echo/echo.bpelArtifacts">

	<import location="echo.wsdl"
		namespace="http://sample.org/wsdl/echo/echo.wsdl" />

	<import location="echo_service.wsdl"
		namespace="http://sample.org/wsdl/echo_service/echo_service.wsdl" />

	<vprop:property name="echoCorrelationData" type="xsd:string" />

	<bpws:propertyAlias messageType="wsdl1:initiateEchoRequest"
		part="echoString" propertyName="tns:echoCorrelationData" />

	<bpws:propertyAlias messageType="wsdl:testResponseMessage"
		part="payload" propertyName="tns:echoCorrelationData" 
		query="/wsdl:testResponse/tns:result" />

	<plnk:partnerLinkType name="EchoCallerPLT">
		<plnk:role name="EchoCaller" portType="wsdl:EchoCallerPT" />
	</plnk:partnerLinkType>

	<plnk:partnerLinkType name="testRequesterPLT">
		<plnk:role name="testProvider" portType="wsdl1:EchoServicePT" />
		<plnk:role name="testReplyReceiver" portType="wsdl:testCallbackPT" />
	</plnk:partnerLinkType>

</definitions>
