###
POST http://localhost:4434/flight  HTTP/1.1
Accept: application/xml
Content-Type: application/xml

<flightReservation date="1590307603704">
    <name>Christian</name>
    <from>Karlsruhe</from>
    <to>Berlin</to>
    <airline>airberlin</airline>
</flightReservation>
###
POST http://localhost:4434/hotel  HTTP/1.1
Accept: application/xml
Content-Type: application/xml

<hotelReservation date="1590307603704">
    <name>Christian</name>
    <hotel>Interconti</hotel>
</hotelReservation>
###
GET http://localhost:4434/flight  HTTP/1.1
Accept: application/xml
###
GET http://localhost:4434/hotel  HTTP/1.1
Accept: application/xml
###
PUT http://localhost:4434/flight/xyz  HTTP/1.1
Accept: text/plain
###
PUT http://localhost:4434/hotel/xyz  HTTP/1.1
Accept: text/plain
###
DELETE http://localhost:4434/flight/  HTTP/1.1
Accept: text/plain
###
DELETE http://localhost:4434/hotel/  HTTP/1.1
Accept: text/plain
###
GET http://localhost:4434/application.wadl HTTP/1.1
Accept: application/xml